export const TEXTS = {
  ge: {
    home: "მთავარი",
    about: "ვინ ვარ მე?",
    services: "სერვისები",
    portfolio: "პორტფოლიო",
    contact: "საკონტაქტო",
    download: "გადმოტვირთე რეზიუმე",
    contactMe: "დამიკავშირდი",
    messageSent: "შეტყობინება გაგზავნილია, მადლობა <3",
    education: "განათლება/ტრენინგები",
    experience: "სამუშაო გამოცდილება",
    skillwill: "სქილვილი",
    front: "ფრონთ-ენდ დეველოპმენტი / რეაქთი, რეაქთ-ნეითივი",
    step: "აიტი აკადემია სტეპი",
    angular: "ფრონტ-ენდ-დეველოპმენტი/ანგულარი",
    bitcamp: "ბითქემფი",
    frontBitcamp: "ფრონტ-ენდ-დეველოპმენტი/რეაქთი",
    davidChikvaidze: "დავით ჩიკვაიძე",
    salesTech: "გაყიდვების ტექნიკები",
    tatiaTura: "თათია ტურაშვილი",
    serviceMang: "სერვის მენეჯმენტი",
    jejelava: "მართვის აკადემია / ალექსანდრე ჯეჯელავა",
    timeMang: "ეფექტური კომუნიკაცია და დროის მართვა",
    gpi: "ჯიპიაი ჰოლდინგი",
    salesMang: "გაყიდვების მენეჯმენტი",
    uni: "საქართველოს ტექნიკური უნივერსიტეტი",
    hlv: "უმაღლესი კლასის მენეჯმენტი",
    specMagistr: "ბიზნეს-ადმინისტრირების მაგისტრი",
    specBacal1: "ტელე-რადიო ჟურნალისტიკა, ბაკალავრი",
    specbacal2: "ბიზნეს-ადმინისტრირება, ბაკალავრი",
    prime: "სადაზღვევო კომპანია პრაიმი",
    corp: "კორპორატიული გაყიდვების მენეჯერი",
    aldagi: "ალდაგი",
    agro: "აგროდაზღვევის გაყიდვების მენეჯერი",
    nvi: "სადაზღვევო კომპანია ნიუვიჟენი",
    liberty: "ლიბერთი ბანკი",
    agroCredit: "აგროდაზღვევის სესხების ოფიცერი",
    crystal: "კრისტალი",
    finca: "ფინკა ბანკი",
    retailSale: "საცალო გაყიდვების სპეციალისტი",
    today: "დღემდე",
    sales: "გაყიდვები",
    management: "მენეჯმენტი",
    magistr: "მაგისტრატურა",
    bacal: "ბაკალავრიატი",
    certificates: "სერთიფიკატები",
    projects: "ჩემი პროექტები",
    reEdu: "RE:EDUCATE",
    backEnd: "ბექ-ენდ დეველოპერი / Node.js, Express.js, Nest.js",
    freelance: "ფრილანსერი",
    mentor: "Front-End დეველოპერი, ანგულარი ლექტორი",
    fullStack: "Full-Stack დეველოპერი",
    bestSoft: "კომპანია ბესთსოფთი",
    frontEnd: "Front-End დეველოპერი",
    soulart: "SoulArt",
    soulartRole:
      "Full-Stack დეველოპერი — გადახდები, ჰოსტინგი, რეფერალური სისტემები, ანალიტიკა, აუქციონები და საიტის სრული ფუნქციონალი",
    shopit: "ShopIt",
    shopitRole:
      "Full-Stack დეველოპერი — ექომერს მარკეტპლეისი (Shopify-ის მსგავსი), გადახდები, ჰოსტინგი, ონლაინ მაღაზიების მართვა და სრული ფუნქციონალი",
    soulartSalesRole:
      "CEO / დირექტორი — მარკეტინგი, გაყიდვები, ბიზნეს სტრატეგია, გუნდის მართვა და კომპანიის სრული ოპერაციული ხელმძღვანელობა",
    expTech: "კომპ. მეცნიერებები და პროგრამირება",
    expSales: "გაყიდვები და ბიზნესი",
    bio: "მაქვს 15 წელზე მეტი გამოცდილება გაყიდვებსა და ბიზნეს მენეჯმენტში — კორპორატიული კლიენტებიდან სტარტაპების დაფუძნებამდე. ბავშვობიდან პროგრამირების სიყვარულმა 2022 წელს ცხოვრების მარშრუტი შეცვალა: პარალელურად დავეუფლე Full-Stack დეველოპმენტს და სწრაფად შევქმენი მრავალმხრივი პლატფორმები, როგორიცაა ექომერს მარკეტპლეისი, აუქციონების სისტემა და რეფერალური პროგრამები. დღეს ვაერთიანებ ბიზნესის და ტექნოლოგიების ცოდნას, რაც მეხმარება წარმატებული პროექტების განხორციელებაში და სხვადასხვა კომპანიებთან თანამშრომლობაში. ასევე, ბოლო 2 წელია თავად ვასწავლი სტუდენტებს ფრონტ-ენდ დეველოპმენტს   ერთ-ერთ აკადემიაში.",
    homeCta: "ავაშენოთ რაღაც ახალი, განსხვავებული...",
    homeBio:
      "მოგესალმებით ჩემს ციფრულ სამყაროში! მე ანი ვარ — Full-Stack დეველოპერი, რომელიც შენს ნებისმიერ იდეას ციფრულ რეალობად გარდაქმნის. ჩემი მიზანია შევქმნა ინოვაციური და ფუნქციონალური პლატფორმები, რომლებიც არა მხოლოდ ლამაზად გამოიყურება, არამედ გეხმარება გაიმარტივო ყოველდღიური საქმიანობა.",
  },

  en: {
    home: "HOME",
    about: "WHO AM I? ",
    services: "SERVICES",
    portfolio: "PORTFOLIO",
    contact: "CONTACT",
    download: "DOWNLOAD CV",
    contactMe: "CONTACT ME ",
    messageSent: "Thank you for your message!",
    education: "EDUCATION / TRAININGS",
    experience: "WORK EXPERIENCE",
    skillwill: "SKILLWILL",
    front: "Front-End Development / React, React-Native",
    step: "IT ACADEMY STEP",
    angular: "Front-End-Development / Angular",
    bitcamp: "BITCAMP",
    frontBitcamp: "Front-End-Development / React",
    davidChikvaidze: "DAVID CHIKVAIDZE",
    salesTech: "Sales Techniques",
    tatiaTura: "TATIA TURASHVILI",
    serviceMang: "Service Managment",
    jejelava: "MANAGEMENT ACADEMY / ALEQSANDRE JEJELAVA",
    timeMang: "Effective communication and Time Management",
    gpi: "GPI HOLDING",
    salesMang: "Sales Management",
    uni: "GEORGIAN TECHNICAL UNIVERSITY",
    hlv: "High Level Management",
    specMagistr: "Master of Business Administration",
    specBacal1: "TV-Radio Journalism, Bachelor",
    specbacal2: "Business Administration, Bachelor",
    prime: "PRIME INSURANCE COMPANY",
    corp: "Corporate Sales Manager",
    aldagi: "ALDAGI",
    agro: "Agro Insurance Sales Manager",
    nvi: "NEW VISION INSURANCE",
    liberty: "LIBERTY BANK",
    agroCredit: "Agro Insurance Credit Officer",
    crystal: "CRYSTAL",
    finca: "FINCA BANK",
    retailSale: "Retail Sales Specialist",
    today: "Till Today",
    sales: "SALES",
    management: "MANAGEMENT",
    magistr: "MASTER'S DEGREE",
    bacal: "BACHELOR'S DEGREE",
    certificates: "CERTIFICATES",
    projects: "MY PROJECTS",
    reEdu: "RE:EDUCATE",
    backEnd: "Back End Developer / Node.js, Express.js, Nest.js",
    freelance: "Freelancer",
    mentor: "Front-End Developer, Angular Lecturer",
    fullStack: "Full-Stack Developer",
    bestSoft: "BESTSOFT COMPANY",
    frontEnd: "Front End Developer",
    soulart: "SoulArt",
    soulartRole:
      "Full-Stack Developer — Payments, Hosting, Referral Systems, Analytics, Auctions & Full Site Functionality",
    shopit: "ShopIt",
    shopitRole:
      "Full-Stack Developer — E-commerce Marketplace Platform (Shopify-like), Payments, Hosting, Online Store Management & Full Functionality",
    soulartSalesRole:
      "CEO / Director — Marketing, Sales, Business Strategy, Team Management & Full Company Operations",
    expTech: "Computer Science & Programming",
    expSales: "Sales & Business",
    bio: "Over 15 years of experience in sales and business management — from corporate clients to founding startups. A childhood passion for programming changed my life's direction in 2022: I mastered Full-Stack development and rapidly built versatile platforms including an e-commerce marketplace, auction system, and referral programs. Today I combine business acumen with technical expertise, enabling me to deliver successful projects and collaborate with diverse companies. For the past 2 years, I've also been teaching front-end development to students at an academy.",
    homeCta: "Let's Build Something Amazing.",
    homeBio:
      "Welcome to my corner of the web! I'm Ani, a passionate full-stack developer with a keen eye for detail and a love for creating engaging digital experiences. From crafting elegant user interfaces to building robust backends, I thrive on bringing ideas to life through clean, efficient code.",
  },
};
