export const TEXTS = {
  ge: {
    home: "მთავარი",
    about: "ვინ ვარ მე?",
    services: "სერვისები",
    portfolio: "პორტფოლიო",
    contact: "საკონტაქტო",
    download: "გადმოტვირთე რეზიუმე",
    contactMe: "დამიკავშირდი",
    messageSent: "შეტყობინება გაგზავნილია, მადლობა <3",
    education: "განათლება/ტრენინგები",
    experience: "სამუშაო გამოცდილება",
    skillwill: "სქილვილი",
    front: "ფრონთ-ენდ დეველოპმენტი / რეაქთი, რეაქთ-ნეითივი",
    step: "აიტი აკადემია სთეფი",
    angular: "ფრონტ-ენდ-დეველოპმენტი/ანგულარი",
    bitcamp: "ბითქემფი",
    frontBitcamp: "ფრონტ-ენდ-დეველოპმენტი/რეაქთი",
    davidChikvaidze: "დავით ჩიკვაიძე",
    salesTech: "გაყიდვების ტექნიკები",
    tatiaTura: "თათია ტურაშვილი",
    serviceMang: "სერვის მენეჯმენტი",
    jejelava: "მართვის აკადემია / ალექსანდრე ჯეჯელავა",
    timeMang: "ეფექტური კომუნიკაცია და დროის მართვა",
    gpi: "ჯიპიაი ჰოლდინგი",
    salesMang: "გაყიდვების მენეჯმენტი",
    uni: "საქართველოს ტექნიკური უნივერსიტეტი",
    hlv: "უმაღლესი კლასის მენეჯმენტი",
    specMagistr: "ბიზნეს-ადმინისტრირების მაგისტრი",
    specBacal1: "ტელე-რადიო ჟურნალისტიკა, ბაკალავრი",
    specbacal2: "ბიზნეს-ადმინისტრირება, ბაკალავრი",
    prime: "სადაზღვევო კომპანია პრაიმი",
    corp: "კორპორატიული გაყიდვების მენეჯერი",
    aldagi: "ალდაგი",
    agro: "აგროდაზღვევის გაყიდვების მენეჯერი",
    nvi: "სადაზღვევო კომპანია ნიუვიჟენი",
    liberty: "ლიბერთი ბანკი",
    agroCredit: "აგროდაზღვევის სესხების ოფიცერი",
    crystal: "კრისტალი",
    finca: "ფინკა ბანკი",
    retailSale: "საცალო გაყიდვების სპეციალისტი",
    today: "დღემდე",
    sales: "გაყიდვები",
    management: "მენეჯმენტი",
    magistr: "მაგისტრატურა",
    bacal: "ბაკალავრიატი",
    certificates: "სერთიფიკატები",
    projects: "ჩემი პროექტები",
  },

  en: {
    home: "HOME",
    about: "WHO AM I? ",
    services: "SERVICES",
    portfolio: "PORTFOLIO",
    contact: "CONTACT",
    download: "DOWNLOAD CV",
    contactMe: "CONTACT ME ",
    messageSent: "Thank you for your message!",
    education: "EDUCATION / TRAININGS",
    experience: "WORK EXPERIENCE",
    skillwill: "SKILLWILL",
    front: "Front-End Development / React, React-Native",
    step: "IT ACADEMY STEP",
    angular: "Front-End-Development / Angular",
    bitcamp: "BITCAMP",
    frontBitcamp: "Front-End-Development / React",
    davidChikvaidze: "DAVID CHIKVAIDZE",
    salesTech: "Sales Techniques",
    tatiaTura: "TATIA TURASHVILI",
    serviceMang: "Service Managment",
    jejelava: "MANAGEMENT ACADEMY / ALEQSANDRE JEJELAVA",
    timeMang: "Effective communication and Time Management",
    gpi: "GPI HOLDING",
    salesMang: "Sales Management",
    uni: "GEORGIAN TECHNICAL UNIVERSITY",
    hlv: "High Level Management",
    specMagistr: "Master of Business Administration",
    specBacal1: "TV-Radio Journalism, Bachelor",
    specbacal2: "Business Administration, Bachelor",
    prime: "PRIME INSURANCE COMPANY",
    corp: "Corporate Sales Manager",
    aldagi: "ALDAGI",
    agro: "Agro Insurance Sales Manager",
    nvi: "NEW VISION INSURANCE",
    liberty: "LIBERTY BANK",
    agroCredit: "Agro Insurance Credit Officer",
    crystal: "CRYSTAL",
    finca: "FINCA BANK",
    retailSale: "Retail Sales Specialist",
    today: "Till Today",
    sales: "SALES",
    management: "MANAGEMENT",
    magistr: "MASTER'S DEGREE",
    bacal: "BACHELOR'S DEGREE",
    certificates: "CERTIFICATES",
    projects: "MY PROJECTS",
  },
};
